project_id = "erqbocersgeghtjadkvw"

[functions.auth-register]
verify_jwt = false

[functions.auth-login]
verify_jwt = false

[functions.ingest-odds]
verify_jwt = false

[functions.ingest-injuries]
verify_jwt = false

[functions.ingest-weather]
verify_jwt = false

[functions.build-features]
verify_jwt = false

[functions.generate-predictions]
verify_jwt = false

[functions.calibrate-model]
verify_jwt = false

[functions.generate-narratives]
verify_jwt = false

[functions.orchestrator]
verify_jwt = false

[functions.generate-pdf]
verify_jwt = false

[functions.generate-tts]
verify_jwt = false

[functions.alert-monitor]
verify_jwt = false

[functions.export-user-data]
verify_jwt = false

[functions.health-check]
verify_jwt = false

[functions.send-weekly-summary]
verify_jwt = false

[functions.send-game-alert]
verify_jwt = false

[functions.send-transactional]
verify_jwt = false

[functions.unsubscribe]
verify_jwt = true